# Generated by Django 4.2.20 on 2025-04-27 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_alter_bookrate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookrate',
            unique_together={('book', 'user')},
        ),
    ]
