# Generated by Django 4.2.20 on 2025-06-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_public',
            new_name='public',
        ),
    ]
