# Generated by Django 4.2.20 on 2025-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_cart_shipping_cost_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='badge',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='light', max_length=100),
        ),
    ]
